<?php
// test3.php - Blue Sky Post Receiver
// Created: 05/06/2026
// Updated: 05/14/2026 - Added post title and description support

ini_set('display_errors', 0); // Hide errors from the mobile app for clean JSON
error_reporting(E_ALL);

// 1. CONFIGURATION
$baseDir = "/var/www/html/tmp/php/uploads/";
$baseUrl = "https://datacommlab.com/tmp/php/uploads/";
$adminEmail = "support@datacommlab.com";

// 2. CAPTURE INCOMING DATA
// Post information
$postTitle       = $_POST['post_title']       ?? '';
$postDescription = $_POST['post_description'] ?? '';

// User profile information
$fname   = $_POST['fname']   ?? 'Guest';
$lname   = $_POST['lname']   ?? 'User';
$email   = $_POST['email']   ?? '';
$phone   = $_POST['phone']   ?? '';
$weixin  = $_POST['weixin']  ?? '';
$address = $_POST['address'] ?? '';
$locPerm = $_POST['use_location'] ?? '0';

// Determine location string
$locationText = ($locPerm === '1') ? "Houston, TX" : "my phone"; // Placeholder for actual GPS logic later
$currentDate = date("F j, Y, g:i a");

// 3. CREATE UNIQUE DIRECTORY
$folderName = preg_replace("/[^a-zA-Z0-9]/", "", $fname) . "_" .
              preg_replace("/[^a-zA-Z0-9]/", "", $lname) . "_" .
              date("YmdHis");
$targetDir = $baseDir . $folderName . "/";

if (!is_dir($targetDir)) {
    mkdir($targetDir, 0755, true);
}

// 4. PROCESS UPLOADS
$uploadedFiles = [];
foreach ($_FILES as $key => $file) {
    if ($file['error'] === UPLOAD_ERR_OK) {
        $safeName = preg_replace("/[^a-zA-Z0-9\._-]/", "_", $file['name']);
        $dest = $targetDir . $safeName;
        if (move_uploaded_file($file['tmp_name'], $dest)) {
            // Check if there was a corresponding caption
            $index = str_replace('file_', '', $key);
            $caption = $_POST['caption_' . $index] ?? '';
            $uploadedFiles[] = ['name' => $safeName, 'caption' => $caption];
        }
    }
}

// 5. BUILD THE HTML POST
$htmlContent = "
<!DOCTYPE html>
<html>
<head>
    <title>{$postTitle}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <style>
        body { font-family: sans-serif; line-height: 1.6; padding: 20px; background: #f4f4f4; }
        .card { max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #007bff; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        .media-item { margin-bottom: 30px; }
        img, video { width: 100%; border-radius: 5px; }
        .caption { font-style: italic; color: #555; margin-top: 5px; background: #fff8e1; padding: 10px; border-left: 4px solid #ffc107; }
        .footer { font-size: 12px; color: #888; text-align: center; margin-top: 20px; }
    </style>
</head>
<body>
    <div class='card'>
        <h1>{$postTitle}</h1>
        {POST_DESCRIPTION_HTML}
        <p><strong>Posted by:</strong> {$fname} {$lname} | <strong>From:</strong> {$locationText} | <strong>Date:</strong> {$currentDate}</p>";

foreach ($uploadedFiles as $item) {
    $ext = strtolower(pathinfo($item['name'], PATHINFO_EXTENSION));
    if (in_array($ext, ['mp4', 'mov', 'webm'])) {
        $htmlContent .= "<div class='media-item'><video controls src='{$item['name']}'></video>";
    } else {
        $htmlContent .= "<div class='media-item'><img src='{$item['name']}'>";
    }
    if ($item['caption']) {
        $htmlContent .= "<p class='caption'>{$item['caption']}</p>";
    }
    $htmlContent .= "</div>";
}

$htmlContent .= "
        <div class='footer'>Generated by Data Communications Lab - Blue Sky Post</div>
    </div>
</body>
</html>";

file_put_contents($targetDir . "index.html", $htmlContent);

// 6. HANDLE DESCRIPTION IN HTML
if (!empty($postDescription)) {
    $descHtml = "<div style='background: #f0f7ff; padding: 15px; border-left: 4px solid #007bff; margin-bottom: 20px; border-radius: 5px;'>\n";
    $descHtml .= "<strong>Description:</strong><br>" . nl2br(htmlspecialchars($postDescription)) . "\n";
    $descHtml .= "</div>";
} else {
    $descHtml = "";
}
$htmlContent = str_replace("{POST_DESCRIPTION_HTML}", $descHtml, $htmlContent);

// 7. BUILD PROFILE AND EMAIL CONTENT
$postcardUrl = $baseUrl . $folderName . "/index.html";

// Profile file
$profileText = "TITLE: $postTitle\nDESCRIPTION: $postDescription\nFNAME: $fname\nLNAME: $lname\nPHONE: $phone\nEMAIL: $email\nWEIXIN: $weixin\nADDRESS: $address\nURL: $postcardUrl\nFOLDER: $folderName\nDATE: $currentDate";
file_put_contents($targetDir . "profile.txt", $profileText);

// 8. PREPARE EMAIL CONTENT
$emailSubject = "New Blue Sky Post: " . $postTitle;
$emailBody = "A new post has been submitted.\n\n";
$emailBody .= "=== POST INFORMATION ===\n";
$emailBody .= "Title: " . $postTitle . "\n";
if (!empty($postDescription)) {
    $emailBody .= "Description: " . $postDescription . "\n";
}
$emailBody .= "\n=== POSTED BY ===\n";
$emailBody .= "Name: " . $fname . " " . $lname . "\n";
$emailBody .= "Email: " . $email . "\n";
$emailBody .= "Phone: " . $phone . "\n";
$emailBody .= "WeChat ID: " . $weixin . "\n";
$emailBody .= "Address: " . $address . "\n";
$emailBody .= "\n=== MEDIA INFORMATION ===\n";
$emailBody .= "Total Files: " . count($uploadedFiles) . "\n";
foreach ($uploadedFiles as $idx => $item) {
    $emailBody .= ($idx + 1) . ". " . $item['name'];
    if (!empty($item['caption'])) {
        $emailBody .= " - Caption: " . $item['caption'];
    }
    $emailBody .= "\n";
}
$emailBody .= "\n=== ACCESS INFORMATION ===\n";
$emailBody .= "Post URL: " . $postcardUrl . "\n";
$emailBody .= "Folder: " . $folderName . "\n";
$emailBody .= "Submitted: " . $currentDate . "\n";
$emailBody .= "IP Address: " . $_SERVER['REMOTE_ADDR'] . "\n";

// 9. SEND EMAIL TO ADMIN
$headers = "From: noreply@datacommlab.com\r\n";
if (!empty($email)) {
    $headers .= "Reply-To: " . $email . "\r\n";
}
$headers .= "Content-Type: text/plain; charset=UTF-8\r\n";

mail($adminEmail, $emailSubject, $emailBody, $headers);

// 10. RESPOND TO MOBILE APP
header('Content-Type: application/json');
echo json_encode([
    'ok' => true,
    'url' => $postcardUrl
]);
exit;

